name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build for multiple platforms
        run: |
          GOOS=darwin GOARCH=amd64 go build -o gincraft-darwin-amd64
          GOOS=linux GOARCH=amd64 go build -o gincraft-linux-amd64
          GOOS=windows GOARCH=amd64 go build -o gincraft-windows-amd64.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: |
            gincraft-darwin-amd64
            gincraft-linux-amd64
            gincraft-windows-amd64.exe

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: binaries

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            gincraft-darwin-amd64
            gincraft-linux-amd64
            gincraft-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
